name: develop

on:
  push:
    branches:
      - main

jobs:
  spring-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Install Sudo 
        run: sudo apt update  && sudo apt install sudo -y

      - name: Install Maven
        run: cd Banking-System-Back && sudo apt update  && sudo apt install maven -y

      - name: Resolve Back
        run: cd calculator && mvn install

      - name: Build the System
        run:  cd calculator && mvn clean package

      - name: Run tests
        run:  cd calculator && mvn test

create-tag:
    runs-on: ubuntu-latest
    needs: [vue-build]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create build tag
      id: tag
      run: |
        BUILD_NUMBER=$(date +%s)
        git tag build-${BUILD_NUMBER}
        git push origin build-${BUILD_NUMBER}

create-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: create package
        run: |
          git checkout ${{github.ref_name}}
          zip -r ${{github.ref_name}}.zip .

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.ref_name}}
          path: ${{github.ref_name}}.zip
