. Faz o buid do codigo (compila ou faz a checagem da sintaxe)
b. Executa os casos de testes definidos (apenas se o passo anterior for
sucesso)
c. Cria uma tag com o nome build_<num>, onde num pode ser qualquer
numero que identifica unicamente a execuça o
d. Cria um pacote zip ou gz com o codigo (apenas se o passo anterior for
sucesso)
e. Adiciona o pacote gerado como um artefato do Workflow no GitHub
(apenas se o passo anterior for sucesso


name: develop

on:
  push:
    branches:
      - main

jobs:
  spring-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Install Sudo 
        run: sudo apt update  && sudo apt install sudo -y

      - name: Install Maven
        run: cd Banking-System-Back && sudo apt update  && sudo apt install maven -y

      - name: Resolve Back
        run: cd calculator && mvn install

      - name: Build the System
        run:  cd calculator && mvn clean package

      - name: Run tests
        run:  cd calculator && mvn test
