name: develop

on:
  push:
    branches:
      - main

jobs:
  spring-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Sudo 
        run: sudo apt update  && sudo apt install sudo -y

      - name: Install Maven
        run: cd Banking-System-Back && sudo apt update  && sudo apt install maven -y

      - name: Resolve Back
        run: cd calculator && mvn install

      - name: Build the System
        run:  cd calculator && mvn clean package

      - name: Run tests
        run:  cd calculator && mvn test
